# Generated by Django 4.1.3 on 2022-12-04 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0002_buku_perpustakaan'),
        ('AdministrasiPeminjam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerpusBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_buku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdministrasiBuku.buku')),
                ('perpustakaan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdministrasiBuku.perpustakaan')),
            ],
            options={
                'db_table': 'Perpus_Buku',
            },
        ),
    ]
