# Generated by Django 4.1.3 on 2022-12-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiPeminjam', '0002_perpusbuku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerpusBuku',
        ),
    ]
