# Generated by Django 4.1.3 on 2022-12-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0002_alter_authuserkapus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuserkapus',
            name='id',
        ),
        migrations.AlterField(
            model_name='authuserkapus',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
