# Generated by Django 4.1.3 on 2022-12-03 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0010_buku_banyak'),
        ('login_logout', '0003_remove_authuserkapus_id_alter_authuserkapus_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserkapus',
            name='perpustakaanKerja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministrasiBuku.perpustakaan'),
        ),
    ]
