# Generated by Django 4.1.3 on 2022-12-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0004_authuserkapus_perpustakaankerja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuserkapus',
            old_name='perpustakaanKerja',
            new_name='perpustakaanKerjaModel',
        ),
        migrations.AddField(
            model_name='authuserkapus',
            name='perpustakaanKerjaChar',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
