# Generated by Django 4.1.3 on 2022-12-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrow',
            name='book',
            field=models.CharField(default='buku', max_length=50),
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='perpustakaan',
            field=models.CharField(default='perpustakaan', max_length=50),
        ),
        migrations.AddField(
            model_name='requestbooking',
            name='perpustakaan',
            field=models.CharField(default='perpustakaan', max_length=50),
        ),
    ]
