# Generated by Django 4.1.3 on 2022-12-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBooking',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp_request', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
