# Generated by Django 4.1.3 on 2022-12-08 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrow',
            name='timestamp_retrieval_limit',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 9)),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='timestamp_return_limit',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 15)),
        ),
    ]
