# Generated by Django 4.1.3 on 2022-12-09 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookborrow_timestamp_retrieval_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrow',
            name='timestamp_retrieval_limit',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 11)),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='timestamp_return_limit',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 17)),
        ),
    ]
