# Generated by Django 4.1.3 on 2022-12-01 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_requestbooking_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbooking',
            name='book',
            field=models.CharField(default='buku', max_length=50),
        ),
        migrations.AlterField(
            model_name='requestbooking',
            name='timestamp_request',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
