# Generated by Django 4.1.3 on 2022-12-01 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_requestbooking_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBorrow',
            fields=[
                ('id_borrow', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp_accepted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(default='Siap Diambil', max_length=50)),
                ('timestamp_return_limit', models.DateField(blank=True, default=datetime.date(2022, 12, 9))),
                ('timestamp_retrieval_limit', models.DateField(null=True)),
            ],
        ),
    ]
