# Generated by Django 4.1.3 on 2022-12-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingPerpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perpus_banget', models.CharField(max_length=50, verbose_name=(('PerpusA',), ('PerpusB',), ('PerpusC',), ('PerpusD',)))),
                ('total_score', models.IntegerField()),
                ('count_score', models.IntegerField()),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=500)),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='nama_perpus_temp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
