# Generated by Django 4.1.3 on 2022-12-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingPerpustakaan', '0002_countrating_rating_nama_perpus_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrating',
            name='nama_perpus_banget',
            field=models.CharField(max_length=50, verbose_name=(('PerpusA',), ('PerpusB',), ('PerpusC',), ('PerpusD',))),
        ),
    ]
