# Generated by Django 4.1.3 on 2022-12-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingPerpustakaan', '0004_alter_countrating_nama_perpus_banget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrating',
            name='nama_perpus_banget',
            field=models.CharField(max_length=50, verbose_name=(('Satu',), ('Dua',), ('Tiga',))),
        ),
    ]
