# Generated by Django 4.1.4 on 2022-12-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RatingPerpustakaan', '0005_alter_countrating_nama_perpus_banget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrating',
            name='nama_perpus_banget',
        ),
    ]
