# Generated by Django 4.1.4 on 2022-12-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RatingPerpustakaan', '0007_alter_countrating_final_score'),
        ('RatingPerpustakaan', '0009_alter_countrating_nama_perpus_banget'),
    ]

    operations = [
    ]
