# Generated by Django 4.1.3 on 2022-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('nama_buku', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('penulis', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'buku',
            },
        ),
    ]
