# Generated by Django 4.1.3 on 2022-12-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='perpustakaan',
            field=models.ManyToManyField(to='AdministrasiBuku.perpustakaan'),
        ),
    ]
