# Generated by Django 4.1.3 on 2022-12-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('nama_buku', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('penulis', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'novel',
            },
        ),
    ]
