# Generated by Django 4.1.3 on 2022-12-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0002_novel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Novel',
        ),
    ]
