# Generated by Django 4.1.3 on 2022-12-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0002_buku_perpustakaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='banyak',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='perpustakaan',
        ),
    ]
