# Generated by Django 4.1.3 on 2022-12-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0003_remove_buku_banyak_remove_buku_perpustakaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.IntegerField()),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministrasiBuku.buku')),
                ('nama_perpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministrasiBuku.perpustakaan')),
            ],
            options={
                'db_table': 'Quantity',
            },
        ),
        migrations.AddField(
            model_name='buku',
            name='perpustakaan',
            field=models.ManyToManyField(through='AdministrasiBuku.Quantity', to='AdministrasiBuku.perpustakaan'),
        ),
    ]
