# Generated by Django 4.1.3 on 2022-12-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buku',
            table='Buku',
        ),
    ]
