# Generated by Django 4.1.3 on 2022-12-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0005_remove_buku_perpustakaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='perpustakaan',
            field=models.ManyToManyField(through='AdministrasiBuku.Quantity', to='AdministrasiBuku.perpustakaan'),
        ),
    ]
