# Generated by Django 4.1.3 on 2022-12-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0006_alter_buku_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buku',
        ),
    ]
