# Generated by Django 4.1.3 on 2022-12-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0006_buku_perpustakaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='kuantitas',
            field=models.IntegerField(default=0),
        ),
    ]
