# Generated by Django 4.1.3 on 2022-12-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0007_alter_quantity_kuantitas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quantity',
            new_name='PerpusBuku',
        ),
        migrations.AlterModelTable(
            name='perpusbuku',
            table='PerpusBuku',
        ),
    ]
