# Generated by Django 4.1.3 on 2022-12-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perpustakaan',
            fields=[
                ('nama', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lokasi', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'perpustakaan',
            },
        ),
    ]
