# Generated by Django 4.1.3 on 2022-12-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrasiBuku', '0009_perpustakaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='banyak',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
