# Generated by Django 4.1.3 on 2022-12-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaranPenambahanBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_buku', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=30)),
                ('nama_penulis', models.CharField(max_length=50)),
                ('nama_penerbit', models.CharField(max_length=50)),
            ],
        ),
    ]
