# Generated by Django 4.1.3 on 2022-12-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_buku', models.CharField(default='', max_length=30)),
                ('nama_penulis', models.CharField(default='', max_length=30)),
                ('isbn', models.BigIntegerField(default=0)),
                ('tersedia', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Buku-buku',
            },
        ),
    ]
