# Generated by Django 4.0.2 on 2022-12-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_buku', models.CharField(max_length=30)),
                ('nama_penulis', models.CharField(max_length=30)),
                ('isbn', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Buku-buku',
            },
        ),
    ]
