# Generated by Django 4.0.2 on 2022-12-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mencari_buku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='isbn',
            field=models.BigIntegerField(),
        ),
    ]
