# Generated by Django 4.0.2 on 2022-12-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mencari_buku', '0002_alter_buku_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='tersedia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buku',
            name='isbn',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buku',
            name='nama_buku',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='buku',
            name='nama_penulis',
            field=models.CharField(default='', max_length=30),
        ),
    ]
