name: Django Tests

on: ['pull_request', 'push']

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        db: [postgres]
        python-version: [3.9]
        include:
          - db: postgres
            db_user: runner
            db_password: ''

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Fikriazain23
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps: 
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -r requirements.txt


      - name: Start PostgreSQL
            if: matrix.db == 'postgres'
            run: |
              sudo systemctl start postgresql.service
              sudo -u postgres createuser -s runner

      - name: Run Pytest
        env:
          DB: ${{ matrix.db }}
          DB_USER: ${{ matrix.db_user }}
          DB_PASSWORD: ${{ matrix.db_password }}
        run: 
          pip install pytest
          pytest
      - name: Django Testing
        env:
          DB: ${{ matrix.db }}
          DB_USER: ${{ matrix.db_user }}
          DB_PASSWORD: ${{ matrix.db_password }}
        run: 
          python3 manage.py test
