name: Django Tests

on: ['pull_request', 'push']

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -r requirements.txt
      - name: Lint with Flake8
        run: 
          pip install flake8
          flake8
      - name: Coverage Report
        run:
          pip install coverage
          coverage run manage.py test
      - name: Django Testing
        run: 
          python3 manage.py test
